### ISSUE TITLE
Proposal: move `bench` under `src/main/test`

### ISSUE THREAD

**Issue by pbailis** [stanford-futuredata/macrobase#147]
Any thoughts? @mamikonyana @kexinrong @sahaana @edgan8 @raininthesun?

**Comment by pbailis** [comment]
Ditto `scripts`... 

Also, @mamikonyana: how is `scripts/benchmark` different than `scripts/bench`? Should we merge them?

**Comment by mamikonyana** [comment]
We should merge `/scripts/benchmark` and `/bench`, I created the former when I had forgotten that we had scripts under `/bench`.

what's the benefit of having `bench` under `src/main/test`? It seems cleaner having python code in a separate high level directory

**Comment by pbailis** [comment]
Great, will work on consolidation.

`bench` is a type of test, would prefer to keep the root directory clean (e.g., Spark, Mesos, don't have this). Alternatively, could create a `tools/` dir?

@kexinrong @edgan8 @sahaana?

**Comment by edgan8** [comment]
I agree with @mamikonyana that it's nice for the toplevel "test" directory be reserved for relatively fast-running correctness tests. We can then have benchmarks in a separate directory since they're probably not going to be run when you want "mvn test". I've been thinking about creating an "experiments" directory where we can have standalone code we use to try certain hypotheses without polluting the main source or the actual correctness tests, what do you guys think? General purpose "scripts" that are broadly useful to normal macrobase usage (if there are any) can then also have their own directory.

**Comment by pbailis** [comment]
I'm okay with an 'experiments' subdir, though we'll need to modify the Maven layout. What were you thinking: creating a submodule?

**Comment by pbailis** [comment]
Done via #160
