### ISSUE TITLE
[Feature Request] Select All as Explanatory Variable

### ISSUE THREAD

**Issue by madcarrot** [stanford-futuredata/macrobase#251]
When dealing with datasets with a large number of columns, it is very inconvenient to select all the columns every time the query is refreshed. Can we add a button to "select all as explanatory variable"?

**Comment by fabuzaid21** [comment]
Ah, okay—it looks like you're using the UI; your slow query times make more sense now. (Unfortunately, the UI is built on an older version of the code, which is much slower. We're going to release an update soon, though.)

In MacroBase SQL, you can select all columns as potentially explanatory variables by using `ON *`. You can check out an example in this tutorial: https://macrobase.stanford.edu/docs/sql/workshop/#getting-started. I recommend using the SQL interface for now, because it should be much faster.
